from selene import browser, have, be
import requests

response = requests.get('http://localhost/theveil/theveil/')
status = response.status_code

def test_start():
    browser.open("/theveil/")
    print('')
    print('Загрузка страницы')
    if status is 200:
        print('Статус код: ', status, ' OK')
    else:
        print('Код: ', status)
        browser.element('[id="reload-button"]').click()

def test_active_button():
    print('')
    print('Главное меню: подсветка разделов')
    browser.element('[class="mainmenu mobile-menu"]>ul>li[class="active"]').should(be.present)
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[4].should(have.no.css_class("active"))

def test_click_on_menu_ind():
    print('')
    print('Главное меню: "index"->"index"')
    browser.element('[id="ind0"]').click()
    browser.should(have.url_containing('/theveil/index.html'))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[0].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[4].should(have.no.css_class("active"))

def test_click_on_menu_plb():
    print('')
    print('Главное меню: "index"->"playbooks"')
    browser.element('[id="plb0"]').click()
    browser.should(have.url_containing('/theveil/playbooks.html'))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[1].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[4].should(have.no.css_class("active"))
    browser.element('[id="ind0"]').click()
    browser.should(have.url_containing('/theveil/index.html'))

def test_click_on_menu_mvs():
    print('')
    print('Главное меню: "index"->"moves"')
    browser.element('[id="mvs0"]').click()
    browser.should(have.url_containing('/theveil/moves.html'))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[2].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[4].should(have.no.css_class("active"))
    browser.element('[id="ind0"]').click()
    browser.should(have.url_containing('/theveil/index.html'))

def test_click_on_menu_tbl():
    print('')
    print('Главное меню: "index"->"tables_custom"')
    browser.element('[id="tbl0"]').click()
    browser.should(have.url_containing('/theveil/tables_custom.html'))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[3].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[4].should(have.no.css_class("active"))
    #Проверка подсветки кнопок меню таблицы
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[0].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[3].should(have.no.css_class("active"))
    browser.element('[id="ind0"]').click()
    browser.should(have.url_containing('/theveil/index.html'))

def test_click_on_menu_glr():
    print('')
    print('Главное меню: "index"->"gallery"')
    browser.element('[id="glr0"]').click()
    browser.should(have.url_containing('/theveil/gallery.html'))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[4].should(have.css_class("active"))
    #Проверка подсветки контрольных кнопок меню галереи
    browser.all('[class ="gallery-controls"]>ul>li')[0].should(have.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[3].should(have.no.css_class("active"))
    browser.element('[id="ind0"]').click()
    browser.should(have.url_containing('/theveil/index.html'))

def test_cross_click_on_menu():
    print('')
    print('Главное меню: кросс-переходы')
    browser.open('/theveil/playbooks.html')
    browser.element('[id="plb0"]').click()
    browser.should(have.url_containing('/theveil/playbooks.html'))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[1].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"]>ul>li')[4].should(have.no.css_class("active"))
    browser.element('[id="mvs0"]').click()
    browser.should(have.url_containing('/theveil/moves.html'))
    browser.element('[id="mvs0"]').click()
    browser.should(have.url_containing('/theveil/moves.html'))
    browser.element('[id="tbl0"]').click()
    browser.should(have.url_containing('/theveil/tables_custom.html'))
    browser.element('[id="tbl0"]').click()
    browser.should(have.url_containing('/theveil/tables_custom.html'))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[3].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[4].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[0].should(have.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu1]>ul>li')[3].should(have.no.css_class("active"))
    browser.element('[id="glr0"]').click()
    browser.should(have.url_containing('/theveil/gallery.html'))
    browser.element('[id="glr0"]').click()
    browser.should(have.url_containing('/theveil/gallery.html'))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[0].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[3].should(have.no.css_class("active"))
    browser.all('[class="mainmenu mobile-menu"][name=menu0]>ul>li')[4].should(have.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[0].should(have.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[1].should(have.no.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[2].should(have.no.css_class("active"))
    browser.all('[class ="gallery-controls"]>ul>li')[3].should(have.no.css_class("active"))
    browser.element('[id="mvs0"]').click()
    browser.should(have.url_containing('/theveil/moves.html'))
    browser.element('[id="plb0"]').click()
    browser.should(have.url_containing('/theveil/playbooks.html'))
    browser.element('[id="glr0"]').click()
    browser.should(have.url_containing('/theveil/gallery.html'))
    browser.element('[id="tbl0"]').click()
    browser.should(have.url_containing('/theveil/tables_custom.html'))
    browser.element('[id="mvs0"]').click()
    browser.should(have.url_containing('/theveil/moves.html'))
    browser.element('[id="glr0"]').click()
    browser.should(have.url_containing('/theveil/gallery.html'))
    browser.element('[id="plb0"]').click()
    browser.should(have.url_containing('/theveil/playbooks.html'))
    browser.element('[id="tbl0"]').click()
    browser.should(have.url_containing('/theveil/tables_custom.html'))
    browser.element('[id="plb0"]').click()
    browser.should(have.url_containing('/theveil/playbooks.html'))

